fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    archive:
        repo: "https://github.com/voxpupuli/puppet-archive.git"
        ref: "v1.1.2"
  symlinks:
    nomad: "#{source_dir}"
